---

- name: undercloud config-download
  gather_facts: no
  hosts: undercloud
  tasks:
    - name: Run config-download
      shell: |
        source {{ stackrc }}
        openstack overcloud config download \
          --config-dir {{ config_download_dir }} \
          --no-preserve-config
      args:
        creates: "{{ config_download_dir }}"
    - name: Init git repo for config-download
      shell: |
        cd {{ config_download_dir }}
        git init
        git add -A .
        git commit -m "Initial commit"
    - name: Generate inventory
      shell: |
        source {{ stackrc }}
        tripleo-ansible-inventory --static-yaml-inventory {{ inventory_path }}
      args:
        creates: "{{ inventory_path }}"
    - name: Create remote tarball of config-download directory
      shell: |
        tar czf {{ config_download_dir }}.tgz {{ config_download_dir }}
      args:
        creates: "{{ config_download_dir ~ '.tgz' }}"
    - name: Fetch remote tarball of config-download directory
      fetch:
        dest: "{{ config_download_dir ~ '.tgz' }}"
        src: "{{ config_download_dir ~ '.tgz' }}"
        fail_on_missing: true
        flat: true
    - name: Fetch inventory
      fetch:
        src: "{{ inventory_path }}"
        dest: "{{ inventory_path }}"
        flat: true
        fail_on_missing: true

- name: Copy inventory and config-download to Tower
  gather_facts: no
  become: true
  hosts: tower
  tasks:
    - name: Copy config-download
      copy:
        dest: "{{ tower_project_dir ~ '/' }}"
        src: "{{ config_download_dir ~ '.tgz' }}"
    - name: Extract config-download
      shell: |
        cd {{ tower_project_dir }}
        tar xzf {{ config_download_dir ~ '.tgz' }}
      args:
        creates: "{{ tower_project_dir ~ '/' ~ config_download_dir ~ '/deploy_steps_playbook.yaml' }}"
    - name: Copy inventory
      copy:
        src: "{{ inventory_path }}"
        dest: "{{ tower_project_dir ~ '/' ~ config_download_dir ~ '/' ~ inventory_path }}"

- name: tower configuration
  gather_facts: no
  hosts: tower-client
  tasks:
    - name: Create Tower organization
      tower_organization:
        tower_host: "{{ tower_host }}"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_verify_ssl: "{{ tower_verify_ssl }}"
        name: "{{ tower_organization_name }}"
        description: "{{ tower_organization_description }}"
    - name: Create Tower project
      tower_project:
        description: "{{ tower_project_description }}"
        name: "{{ tower_project_name }}"
        organization: "{{ tower_organization_name }}"
        local_path: "{{ config_download_dir }}"
        tower_host: "{{ tower_host }}"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_verify_ssl: "{{ tower_verify_ssl }}"
    - name: Create Tower inventory
      tower_inventory:
        name: "{{ tower_inventory_name }}"
        description: "{{ tower_inventory_description }}"
        organization: "{{ tower_organization_name }}"
        tower_host: "{{ tower_host }}"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_verify_ssl: "{{ tower_verify_ssl }}"
